keycloak:
  admin:
    username: "root"
    password: "root"
  url: "https://my.domain.com/keycloak"
  realm: "mytestingrealm"
  host:
    domain: "my.domain.com"
    path: "/keycloak"

webApp:
  url: "https://my-webapp.com"

users:
- firstName: "Willy"
  lastName: "Wonka"
  email: "willy@wonka.xyz"
  username: "willywonka999"
  password: "123456"

customEnv:
  client:
    oidc:
      enabled: false
      id: "mytestclient"
      realm: "mytestrealm"
    saml:
      enabled: false
      id: "mytestclient"
      realm: "mytestrealm"
  createCustomMappers: false
