keycloak:
  settings:
    admin:
      username: "root"
      password: "root"
    url: "https://bgu-219-latest.runailabs-cs.com/itays-idp-server"
    host:
      domain: "bgu-219-latest.runailabs-cs.com"
      path: "/itays-idp-server"

realm:
  name: my-org

groups:
  - name: admin-group
  - name: developer-group
  - name: read-only-group

users:
  - email: john.doe@example.com
    password: "123456"
    username: john.doe
    first-name: John
    last-name: Doe
    group: admin-group
  - email: jane.smith@example.com
    password: "123456"
    username: jane.smith
    first-name: Jane
    last-name: Smith
    group: developer-group
  - email: bob.brown@example.com
    password: "123456"
    username: bob.brown
    first-name: Bob
    last-name: Brown
    group: read-only-group

clients:
  - type: oidc
    id: my-oidc-client
    webAppURL: https://my-webapp.com
  - type: saml
    id: my-saml-client
    webAppURL: https://my-webapp.com
