keycloak:
  settings:
    admin:
      username: "root"
      password: "root"
    url: "https://bgu-219-latest.runailabs-cs.com/itays-idp-server"
    host:
      domain: "bgu-219-latest.runailabs-cs.com"
      path: "/itays-idp-server"

realm:
  name: my-org

users:
  - email: john.doe@example.com
    password: "123456"
    username: john.doe
    first-name: John
    last-name: Doe
    group: admin-group
  - email: jane.smith@example.com
    password: "123456"
    username: jane.smith
    first-name: Jane
    last-name: Smith
    group: developer-group
  - email: itzik@example.com
    password: "123456"
    username: itzikitzik
    first-name: Itz
    last-name: Ick
    group: read-only-group
  - email: jacky.fox@example.com
    password: "123456"
    username: jacky.fox
    first-name: Jacky
    last-name: Fox
    group: read-only-group
  - email: blip.blop@example.com
    password: "123456"
    username: blip.blop
    first-name: Blip
    last-name: Blop
    group: read-only-group

clients:
  - type: oidc
    id: my-oidc-client
    webAppURL: https://my-webapp.com
  - type: saml
    id: my-saml-client
    webAppURL: https://my-webapp.com
