  configMap:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: keycloak-config
    data:
      KEYCLOAK_ADMIN_USERNAME: {{ .Values.keycloak.admin.username }}
      KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password }}
      KEYCLOAK_URL: {{ .Values.keycloak.url }}
      KEYCLOAK_REALM: {{ .Values.keycloak.realm }}
      KEYCLOAK_HOST_DOMAIN: {{ .Values.keycloak.host.domain }}
      KEYCLOAK_HOST_PATH: {{ .Values.keycloak.host.path }}
      WEBAPP_URL: {{ .Values.webApp.url }}
      CUSTOMENV_CLIENT_OIDC_ENABLED: {{ .Values.customEnv.client.oidc.enabled }}
      CUSTOMENV_CLIENT_OIDC_ID: {{ .Values.customEnv.client.oidc.id }}
      CUSTOMENV_CLIENT_OIDC_REALM: {{ .Values.customEnv.client.oidc.realm }}
      CUSTOMENV_CLIENT_SAML_ENABLED: {{ .Values.customEnv.client.saml.enabled }}
      CUSTOMENV_CLIENT_SAML_ID: {{ .Values.customEnv.client.saml.id }}
      CUSTOMENV_CLIENT_SAML_REALM: {{ .Values.customEnv.client.saml.realm }}
      CUSTOMENV_CREATE_CUSTOM_MAPPERS: {{ .Values.customEnv.createCustomMappers }}