name: Release Helm Chart

on:
  push:
    tags:
      - "v*"  # Trigger the workflow on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0  # Set your preferred Helm version

      - name: Package Helm chart
        run: helm package <chart-directory>
        # Replace <chart-directory> with the path to your Helm chart, e.g., ./charts/my-chart

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Helm chart to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./*.tgz
          asset_name: "my-chart-${{ github.ref_name }}.tgz"
          asset_content_type: application/gzip
