# This workflow will:

# 1) Trigger on tags that start with v (e.g., v1.0.0).
# 2) Package the Helm chart located in <chart-directory>.
# 3) Create a GitHub Release and upload the packaged .tgz chart file as an asset.

name: Release Helm Chart

on:
  push:
    tags:
      - "v*"  # Trigger the workflow on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0  # Set your preferred Helm version

      - name: Package Helm chart
        run: helm package .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Helm chart to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./*.tgz
          asset_name: "keycloak3r-${{ github.ref_name }}.tgz"
          asset_content_type: application/gzip
